version: '3'
services:
    mysql:
        container_name: dotnet-todo-db
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: database
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - dotnet-todo

networks:
  dotnet-todo:
    driver: "bridge"
    external: true